# Generated by Django 4.2.7 on 2023-11-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('frequency', models.DurationField(default='1 day', verbose_name='периодичность')),
                ('treasure', models.CharField(max_length=255, verbose_name='вознаграждение')),
                ('duration', models.DurationField(verbose_name='длительность')),
                ('public', models.CharField(choices=[('public', 'Опубликовать'), ('not public', 'Не публиковать')], verbose_name='публичность')),
            ],
        ),
    ]
