# Generated by Django 4.2.7 on 2023-11-15 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0003_alter_habit_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.DurationField(default='24:00:00', verbose_name='периодичность'),
        ),
    ]
