# Generated by Django 4.2.7 on 2023-11-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_creator_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.DurationField(default=datetime.timedelta(days=1), verbose_name='периодичность'),
        ),
    ]
