# Generated by Django 4.2.7 on 2023-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_options_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='treasure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение'),
        ),
    ]
