# Generated by Django 4.2.7 on 2023-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_treasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='pleasantness',
            field=models.CharField(choices=[('pleasant', 'Приятная привычка'), ('unpleasant', 'Привычка')], default='unpleasant', verbose_name='приятность'),
        ),
    ]
